[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "gcc", "gnumake", "pkg-config"]

[phases.install]
cmds = ["npm install", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "node server.js"
